# Generated by Django 4.2.4 on 2023-08-09 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_remove_historicalcurrencyvalue_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyvalue',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 22, 12, 12, 634859)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcurrencyvalue',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 22, 12, 57, 828355, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
