# Generated by Django 4.2.4 on 2023-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_currencyvalue_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyvalue',
            name='is_scan_on',
            field=models.BooleanField(default=False, verbose_name='Currency scan is on'),
        ),
        migrations.AddField(
            model_name='historicalcurrencyvalue',
            name='is_scan_on',
            field=models.BooleanField(default=False, verbose_name='Currency scan is on'),
        ),
        migrations.AlterField(
            model_name='currencyvalue',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Currency short code'),
        ),
        migrations.AlterField(
            model_name='currencyvalue',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Currency name'),
        ),
        migrations.AlterField(
            model_name='currencyvalue',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Currency rate to USD'),
        ),
        migrations.AlterField(
            model_name='currencyvalue',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Currency last update'),
        ),
        migrations.AlterField(
            model_name='historicalcurrencyvalue',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Currency rate to USD'),
        ),
        migrations.AlterField(
            model_name='historicalcurrencyvalue',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Currency last update'),
        ),
    ]
