# Generated by Django 4.2.4 on 2023-08-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_currencyvalue_is_scan_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvalue',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='Currency name'),
        ),
    ]
