# Generated by Django 4.2.4 on 2023-08-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_alter_currencyvalue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvalue',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Currency short code'),
        ),
    ]
