# Generated by Django 4.2.4 on 2023-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_alter_currencyvalue_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvalue',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Currency rate to USD'),
        ),
        migrations.AlterField(
            model_name='historicalcurrencyvalue',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Currency rate to USD'),
        ),
    ]
