# Generated by Django 4.2.4 on 2023-08-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0008_alter_currencyvalue_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvalue',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Currency short code'),
        ),
    ]
