# Generated by Django 4.2.4 on 2023-08-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0009_alter_currencyvalue_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvalue',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Currency name'),
        ),
    ]
