version: '3.3'
name: currency_monitor

services:


  # nginx:
  #   image: nginx:1.19.3
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - ../docs/:/usr/share/nginx/html/api/docs/
  #     - static_value:/etc/nginx/html/static/
  #     - media_value:/etc/nginx/html/media/
  #   container_name: nginx
  #   depends_on:
  #     - back
  #     - frontend

  db:
    image: postgres:13.0-alpine
    ports: 
      - 5432:5432
    command: postgres -c listen_addresses=*
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: postgres

  redis:
    image: redis:6.0.9-alpine
    ports:
      - 6379:6379

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5555:5555
    depends_on:
      - redis
  
  worker:
    build:
      context: .
      dockerfile: celery.Dockerfile
    environment:
      - REDIS_HOST=redis://redis:6379/0
    depends_on:
      - redis


  back:
    build:
      context: .
      dockerfile: django.Dockerfile
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/staticfiles/

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/usr/share/nginx/html/static/
    container_name: nginx
    depends_on:
      - back

volumes:
  db_value:
  static_value:

