version: '3.3'
name: currency_monitor

services:
  db:
    image: postgres:13.0-alpine
    ports: 
      - 54322:5432
    command: postgres -c listen_addresses=*
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: postgres

  redis:
    image: redis:6.0.9-alpine

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis
  
  worker:
    build:
      context: ../currency_monitor
      dockerfile: celery.Dockerfile
    environment:
      - REDIS_HOST=redis://redis:6379/0
    depends_on:
      - redis
    env_file:
      - ./.env 


  back:
    build:
      context: ../currency_monitor
      dockerfile: django.Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/staticfiles/

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/usr/share/nginx/html/static/
    container_name: nginx
    depends_on:
      - back

volumes:
  db_value:
  static_value:

